### ISSUE TITLE
请求添加一些新的图标。

### ISSUE THREAD

**Issue by Fddh2012** [Vbaethon/HOMOMIX#4]
建议添加一些大鸡场的图标。
我使用下来需要但是缺失的：
Bing：
![image](https://github.com/user-attachments/assets/0752277b-bffe-4615-91e1-24b97cd63f32)
Bahamut
![image](https://github.com/user-attachments/assets/5a02ee25-344b-48e4-9e70-a6f5695a5862)
Pixiv
![image](https://github.com/user-attachments/assets/d50de3ed-cdc9-4299-81bc-e52d4443c92b)
Scholar
![image](https://github.com/user-attachments/assets/33de63a2-ebc2-4247-92ec-bde02bf2a30a)
GFW list
没错，我的确需要一个图标来表示这东西。
DIRECT
这个也不知道是我的问题还是怎么了，没找到能直接表达意思的图标

**Comment by Vbaethon** [comment]
done，DIRECT 抽象表达用抽象标志
