### ISSUE TITLE
我需要一只猪头图标，没错，就是猪头图标。

### ISSUE THREAD

**Issue by Fddh2012** [Vbaethon/HOMOMIX#5]

**Comment by ab00ky** [comment]
Confused

**Comment by Fddh2012** [comment]
> 拒绝

啊？？？？

**Comment by Vbaethon** [comment]
> > 拒绝
> 
> 啊？？？？

有猪头

**Comment by Fddh2012** [comment]
> > > 拒绝
> > 
> > 
> > 啊？？？？
> 
> 有猪头

我知道啊，只是有点不明白他“Confused”了个什么。
另外这issues不是已经Closed么？
