### ISSUE TITLE
[bug] 最近的更新是不是把图标尺寸搞混了？为什么等高版本变得和满高版本一样了？

### ISSUE THREAD

**Issue by Fddh2012** [Vbaethon/HOMOMIX#6]
![image](https://github.com/user-attachments/assets/0a0b9a53-d2e3-4bfe-9953-e4f313198956)
![image](https://github.com/user-attachments/assets/993843c2-dccb-4c04-8424-4f63cc9a04c0)
![image](https://github.com/user-attachments/assets/41d58f75-1996-4407-889d-e65260d1884e)
![image](https://github.com/user-attachments/assets/56117d82-33a3-49a6-90bb-1b3b9fe2888a)
![image](https://github.com/user-attachments/assets/a4088db6-a7f1-4852-b493-574d484e56e1)
![image](https://github.com/user-attachments/assets/9f60689d-579e-4d6e-be28-14a3d78bacd9)
![image](https://github.com/user-attachments/assets/4df2b369-099c-40a9-b505-9b26db95f868)
![image](https://github.com/user-attachments/assets/ff67c120-c03f-4167-ba8e-eeec9a055856)
![image](https://github.com/user-attachments/assets/77d5d022-a357-4c06-aeba-a0b71d060544)
![image](https://github.com/user-attachments/assets/f0b8fe41-4aad-4d74-9057-252480972e1f)
![image](https://github.com/user-attachments/assets/c8c35580-76eb-47d7-8e8d-bbbdf78b2206)
![image](https://github.com/user-attachments/assets/f8cfcd2d-b02f-43a7-8e1a-0e0a829c24c2)
![image](https://github.com/user-attachments/assets/6bcec572-b773-4061-a5d9-b5fe1fa9f319)
![image](https://github.com/user-attachments/assets/dafa29f5-8e50-46b7-bf03-53802b5538bf)
![image](https://github.com/user-attachments/assets/8224f60c-0bc3-49c6-9392-02e27f224475)
![image](https://github.com/user-attachments/assets/09d09307-2fee-4d94-aec6-54d4fa426dd5)
![image](https://github.com/user-attachments/assets/4ee64e9d-816b-4c8b-a91e-9bb09a0db1dd)
![image](https://github.com/user-attachments/assets/7c949d52-6fbc-4756-be13-e220d9ec5a98)
![image](https://github.com/user-attachments/assets/e64963b1-e3f3-4a30-8e34-98940a567bc2)
![image](https://github.com/user-attachments/assets/2c25f6f5-6d5d-49d5-b050-c08ded5b41ca)

**Comment by Vbaethon** [comment]
已解决
